//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ams_documents
    {
        public int doc_key { get; set; }
        public string doc_title { get; set; }
        public string doc_type { get; set; }
        public Nullable<System.DateTime> doc_created_date { get; set; }
        public Nullable<int> doc_created_by { get; set; }
    
        public virtual ams_users ams_users { get; set; }
    }
}
