//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ams_equipments
    {
        public int equ_key { get; set; }
        public Nullable<System.DateTime> equ_created_date { get; set; }
        public Nullable<System.DateTime> equ_expiry_date { get; set; }
        public Nullable<int> equ_user_key { get; set; }
        public string equ_serial_number { get; set; }
        public string equ_manufacturer { get; set; }
        public string equ_type { get; set; }
    
        public virtual ams_users ams_users { get; set; }
    }
}
