//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ams_parts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ams_parts()
        {
            this.ams_sub_parts = new HashSet<ams_sub_parts>();
        }
    
        public int prt_key { get; set; }
        public Nullable<int> prt_equ_key { get; set; }
        public string prt_title { get; set; }
        public Nullable<int> prt_added_by { get; set; }
        public Nullable<System.DateTime> prt_created_date { get; set; }
    
        public virtual ams_equipments ams_equipments { get; set; }
        public virtual ams_users ams_users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ams_sub_parts> ams_sub_parts { get; set; }
    }
}
