//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AMSEntities : DbContext
    {
        public AMSEntities()
            : base("name=AMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ams_documents> ams_documents { get; set; }
        public virtual DbSet<ams_equipments> ams_equipments { get; set; }
        public virtual DbSet<ams_items> ams_items { get; set; }
        public virtual DbSet<ams_parts> ams_parts { get; set; }
        public virtual DbSet<ams_sub_parts> ams_sub_parts { get; set; }
        public virtual DbSet<ams_users> ams_users { get; set; }
        public virtual DbSet<ams_websites> ams_websites { get; set; }
    }
}
